experiment: "test/miccai/autoencoder/mse/masked"
trainer:
    accelerator: "gpu"
    devices: 1
    max_epochs: 100
    log_every_n_steps: 1
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    fast_dev_run: False
    profiler: False
    reload_dataloaders_every_n_epochs: 0
model:
  module: "lightning_modules"
  name: "GANAutoencoderModule"
  kwargs: {
    "generator_model": {
      module: "models",
      name: "CompletionNetwork",
      kwargs: {
        "in_channels": 4,
        "out_channels": 3,
        "features": 8
      }
    },
    "discriminator_model": {
      module: "models",
      name: "Discriminator",
      kwargs: {
        "in_channels": 3,
        "out_channels": [32, 64, 128, 1],
        "kernel_sizes": [5, 5, 5, 5],
        "strides": [2, 2, 2, 2]
      }
    },
    "generator_optimizer": {
      module: "torch.optim",
      name: "AdamW",
      kwargs: {
        "lr": 1.e-3,
        "betas": [0.9, 0.999]
      }
    },
    "alpha": 1.e-1,
    "discriminator_optimizer": {
      module: "torch.optim",
      name: "AdamW",
      kwargs: {
        "lr": 1.e-4,
        "betas": [0.9, 0.999]
      }
    },
    "generator_scheduler": null,
    "discriminator_scheduler": null
  }
data:
  module: "lightning_data_modules"
  name: "ImageHomographyMaskDataModule"
  kwargs: {
    "dataframe": "22_11_09_deep_log_pre_processed_test_train_no_nan.pkl",
    "prefix": "/media/martin/Samsung_T5/data/endoscopic_data/cholec80_frames",
    "rho": 60,
    "train_split": 0.8,
    "batch_size": 32,
    "num_workers": 2,
    "random_state": 42,
    "tolerance": 0.2,
    "train_transforms": [
      {'chance': 1.0, 'module': 'imgaug.augmenters',                'type': 'Resize',                     'kwargs': {'size': {'height': 120, 'width': 160}}},
      {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'MultiplyAndAddToBrightness', 'kwargs': {'mul': [0.5, 1.5], 'add': [30, 30]}},
      {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'Grayscale',                  'kwargs': {}},
      {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'ChangeColorTemperature',     'kwargs': {'kelvin': [3000, 15000]}},
      {'chance': 0.2, 'module': 'imgaug.augmenters.imgcorruptlike', 'type': 'Contrast',                   'kwargs': {'severity': 1}},
      {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'GaussianBlur',               'kwargs': {}},
      {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'MotionBlur',                 'kwargs': {'k': 15, 'angle': [-45, 45]}},
      {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'AdditiveGaussianNoise',                 'kwargs': {'scale': [0, 51]}},
      {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'Cutout',                 'kwargs': {'nb_iterations': [1, 5], 'cval': 0, 'squared': False}}
    ],
    "val_transforms": [
      {'chance': 1.0, 'module': 'imgaug.augmenters',                'type': 'Resize',                     'kwargs': {'size': {'height': 120, 'width': 160}}},
    ],
    "test_transforms": [
      {'chance': 1.0, 'module': 'imgaug.augmenters',                'type': 'Resize',                     'kwargs': {'size': {'height': 120, 'width': 160}}},
    ]
  }
