experiment: 'test/miccai/conv_homography_predictor/phantom/resnet34'
lightning_module: 'ConvHomographyPredictorModule'
lightning_data_module: 'ImageSequenceDataModule'
model_checkpoint: 
    monitor: 'val/loss'
    mode: 'min'
trainer:
    accelerator: 'gpu'
    devices: 1
    max_epochs: 100
    log_every_n_steps: 1
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    fast_dev_run: False
    profiler: False
data:
    pkl_name: 'pre_processed_10th_frame_log_test_train_no_nan.pkl'
    pkl_path: '21_11_25_first_test_data_frames'
    kwargs:
        train_split: 0.8
        batch_size: 16
        num_workers: 4
        random_state: 42
        tolerance: 0.2 # change this tolerance
        seq_len: 10
        frame_increment: 1
        frames_between_clips: 10 # seq_len*frame_increment
        random_frame_offset: False
        train_spectral_transforms:
            - {'chance': 0.4, 'module': 'imgaug.augmenters',                'type': 'MultiplyAndAddToBrightness', 'kwargs': {'mul': [0.5, 1.5], 'add': [30, 30]}}
            - {'chance': 0.4, 'module': 'imgaug.augmenters',                'type': 'Grayscale',                  'kwargs': {}}
            - {'chance': 0.4, 'module': 'imgaug.augmenters',                'type': 'ChangeColorTemperature',     'kwargs': {'kelvin': [3000, 15000]}}
            - {'chance': 0.4, 'module': 'imgaug.augmenters.imgcorruptlike', 'type': 'Contrast',                   'kwargs': {'severity': 1}}
            - {'chance': 0.4, 'module': 'imgaug.augmenters',                'type': 'AdditiveGaussianNoise',      'kwargs': {'scale': [0, 51]}}
            - {'chance': 0.3, 'module': 'imgaug.augmenters',                'type': 'GaussianBlur',               'kwargs': {}}
            - {'chance': 0.3, 'module': 'imgaug.augmenters.imgcorruptlike', 'type': 'Fog',                        'kwargs': {'severity': 2}}
        train_geometric_transforms:
            - {'chance': 0.5, 'module': 'imgaug.augmenters', 'type': 'Flipud', 'kwargs': {}}
            - {'chance': 0.5, 'module': 'imgaug.augmenters', 'type': 'Fliplr', 'kwargs': {}}
        val_spectral_transforms: null
        val_geometric_transforms: null
        test_spectral_transforms: null
        test_geometric_transforms: null
        load_images: True
callbacks: {}
model:
    predictor: {
        module: "models",
        name: "VarResNet",
        kwargs: {
            "in_channels": 27, # (seq_len-1)*3
            "out_features": 8,
            "name": "resnet34",
            "pretrained": True
        }
    }
    optimizer: {
        module: "torch.optim",
        name: "Adam",
        kwargs: {
            "lr": 3.e-4,
            "betas": [0.9, 0.999]
        }
    }
    loss: {
        module: "torch.nn",
        name: "PairwiseDistance",
        kwargs: {}
    } 
