experiment: 'feature_lstm'
lightning_module: 'FeatureLSTMModule'
lightning_data_module: 'ImageSequenceDataModule'
model_checkpoint: 
    monitor: 'val/distance'
    mode: 'min'
trainer:
    gpus: 1
    max_epochs: 20
    log_every_n_steps: 1
    limit_train_batches: 0.01
    limit_val_batches: 0.01
    limit_test_batches: 0.01
    fast_dev_run: False
    profiler: False
    reload_dataloaders_every_n_epochs: 0
data:
    pkl_name: 'test_train_log.pkl'
    pkl_path: '21_11_25_first_test_data_frames'
    train_split: 0.8
    batch_size: 1
    num_workers: 0
    random_state: 42
    tolerance: 0.2 # change this tolerance
    seq_len: 20
    frame_increment: 10
    train_transforms:
        - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'MultiplyAndAddToBrightness', 'kwargs': {'mul': [0.5, 1.5], 'add': [30, 30]}}
        - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'Grayscale',                  'kwargs': {}}
        - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'ChangeColorTemperature',     'kwargs': {'kelvin': [3000, 15000]}}
        - {'chance': 0.2, 'module': 'imgaug.augmenters.imgcorruptlike', 'type': 'Contrast',                   'kwargs': {'severity': 1}}
        - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'GaussianBlur',               'kwargs': {}}
        - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'MotionBlur',                 'kwargs': {'k': 15, 'angle': [-45, 45]}}
        - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'AdditiveGaussianNoise',                 'kwargs': {'scale': [0, 51]}}
        - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'Cutout',                 'kwargs': {'nb_iterations': [1, 5], 'cval': 0, 'squared': False}}
    val_transforms: null
    test_transforms: null
model:
    backbone: {
        'name': 'ResNet-50',
        'kwargs': {
            'pretrained': False
        }
    }
    head: {
        'kwargs': {
            'input_size': 512,
            'hidden_size': 512, 
            'batch_first': False  # seq x batch x....
        }
    }
    lr: 1.e-4
    betas: [0.9, 0.999]
    log_n_steps: 500
