experiment: 'miccai/feature_lstm/phantom/resnet34/frame_increment_1/transforms'
lightning_module: 'FeatureLSTMModule'
lightning_data_module: 'ImageSequenceDuvDataModule'
model_checkpoint: 
    monitor: 'val/loss'
    mode: 'min'
trainer:
    accelerator: 'gpu'
    devices: 1
    max_epochs: 50
    log_every_n_steps: 1
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    fast_dev_run: False
    profiler: False
    reload_dataloaders_every_n_epochs: 1
data:
    pkl_name: 'pre_processed_10th_frame_log_test_train_no_nan.pkl'
    pkl_path: '21_11_25_first_test_data_frames'
    train_split: 0.8
    batch_size: 16
    num_workers: 4
    random_state: 42
    tolerance: 0.2 # change this tolerance
    seq_len: 20
    frame_increment: 1
    frames_between_clips: 1 # seq_len*frame_increment
    random_frame_offset: False
    train_transforms:
        - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'MultiplyAndAddToBrightness', 'kwargs': {'mul': [0.5, 1.5], 'add': [30, 30]}}
        - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'Grayscale',                  'kwargs': {}}
        - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'ChangeColorTemperature',     'kwargs': {'kelvin': [3000, 15000]}}
        - {'chance': 0.2, 'module': 'imgaug.augmenters.imgcorruptlike', 'type': 'Contrast',                   'kwargs': {'severity': 1}}
        - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'AdditiveGaussianNoise',                 'kwargs': {'scale': [0, 51]}}
        - {'chance': 0.1, 'module': 'imgaug.augmenters',                'type': 'GaussianBlur',           'kwargs': {}}
        - {'chance': 0.1, 'module': 'imgaug.augmenters.imgcorruptlike', 'type': 'Fog',                    'kwargs': {'severity': 2}}
        - {'chance': 0.5, 'module': 'imgaug.augmenters',                'type': 'HorizontalFlip',         'kwargs': {}}
        - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'Crop',                   'kwargs': {'percent': !!python/tuple [0., 0.4]}}
        - {'chance': 0.1, 'module': 'imgaug.augmenters.imgcorruptlike', 'type': 'Fog',                    'kwargs': {'severity': 2}}
    val_transforms: null
    test_transforms: null
    load_images: True
callbacks: {}
model:
    encoder: {
        module: "models",
        name: "VarResNet",
        kwargs: {
            "in_channels": 3,
            "out_features": 32,
            "name": "resnet34",
            "pretrained": True
        }
    }
    lstm: {
        module: "torch.nn",
        name: "LSTM",
        kwargs: {
            "input_size": 40, # out_features + 8
            "hidden_size": 64
        }
    }
    head: [
        {
            module: "torch.nn",
            name: "Linear",
            kwargs: {
                "in_features": 64,
                "out_features": 8
            }
        }
    ]
    optimizer: {
        module: "torch.optim",
        name: "Adam",
        kwargs: {
            "lr": 5.e-4,
            "betas": [0.9, 0.999]
        }
    }
    loss: {
        module: "torch.nn",
        name: "PairwiseDistance",
        kwargs: {}
    }
