experiment: 'miccai/feature_lstm/cholec80/resnet34/no_motion_prior/cosine_similarity'
lightning_module: 'FeatureLSTMModule'
lightning_data_module: 'ImageSequenceDuvDataModule'
model_checkpoint: 
    monitor: 'val/loss'
    mode: 'min'
trainer:
  accelerator: gpu
  devices: 1
  fast_dev_run: false
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 1
  max_epochs: 100
  profiler: false
  reload_dataloaders_every_n_epochs: 1
data:
    pkl_name: '22_11_09_deep_pre_processed_frame_increment_5_frames_between_clips_5_log_test_train_no_nan.pkl'
    pkl_path: 'cholec80_single_video_frames_cropped'
    train_split: 0.8
    batch_size: 8
    num_workers: 8
    random_state: 42
    tolerance: 0.2 # change this tolerance
    seq_len: 60
    frame_increment: 1
    frames_between_clips: 60 # seq_len*frame_increment
    random_frame_offset: False
    train_transforms:
        - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'MultiplyAndAddToBrightness', 'kwargs': {'mul': [0.5, 1.5], 'add': [30, 30]}}
        - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'Grayscale',                  'kwargs': {}}
        - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'ChangeColorTemperature',     'kwargs': {'kelvin': [3000, 15000]}}
        - {'chance': 0.2, 'module': 'imgaug.augmenters.imgcorruptlike', 'type': 'Contrast',                   'kwargs': {'severity': 1}}
        - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'AdditiveGaussianNoise',                 'kwargs': {'scale': [0, 51]}}
        - {'chance': 0.1, 'module': 'imgaug.augmenters',                'type': 'GaussianBlur',           'kwargs': {}}
        - {'chance': 0.1, 'module': 'imgaug.augmenters.imgcorruptlike', 'type': 'Fog',                    'kwargs': {'severity': 2}}
    val_transforms: null
    test_transforms: null
    load_images: True
callbacks: {}
model:
    encoder: {
        module: "models",
        name: "VarResNet",
        kwargs: {
            "in_channels": 3,
            "out_features": 1024,
            "name": "resnet34",
            "pretrained": False
        }
    }
    lstm: {
        module: "torch.nn",
        name: "LSTM",
        kwargs: {
            "input_size": 1024,
            "hidden_size": 1024
        }
    }
    head: [
        {
            module: "torch.nn",
            name: "Linear",
            kwargs: {
                "in_features": 1024,
                "out_features": 8
            }
        }
    ]
    optimizer: {
        module: "torch.optim",
        name: "Adam",
        kwargs: {
            "lr": 3.e-4,
            "betas": [0.9, 0.999]
        }
    }
    loss: {
        module: "torch.nn",
        name: "CosineSimilarity",
        kwargs: {}
    }
