experiment: 'predictive_horizon'
lightning_module: 'PredictiveHorizonModule'
lightning_data_module: 'VideoDataModule'
trainer:
    gpus: 1
    max_epochs: 20
    log_every_n_steps: 1000
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    fast_dev_run: False
    profiler: False
data:
    meta_df: 'cholec80_transforms.pkl'
    subset_length: 10  # number of videos to take from meta_df, set to null to use full df
    train_metadata: 'train_metadata.pkl'
    val_metadata: 'val_metadata.pkl'
    test_metadata: 'test_metadata.pkl'
    clip_length_in_frames: 15
    frames_between_clips: 1
    frame_rate: 5  # re-sample framerate, total of clip_length_in_frames*frame_rate frames covered
    train_split: 0.8
    batch_size: 16
    num_workers: 8
    random_state: 42
model:
    shape: [3, 480, 640]
    lr: 1.e-4
    betas: [0.9, 0.999]
    log_n_steps: 500
    backbone: 'resnet34'
    preview_horizon: 14  # = clip_length_in_frames - 1
