experiment: 'predictive_horizon'
lightning_module: 'PredictiveHorizonModule'
lightning_data_module: 'VideoDataModule'
trainer:
    gpus: 1
    max_epochs: 20
    log_every_n_steps: 10
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    fast_dev_run: False
    profiler: False
data:
    meta_df: 'cholec80_dummy_transforms_endoscopic_view.pkl'
    subset_length: 10  # number of videos to take from meta_df, set to null to use full df
    train_metadata: 'train_metadata.pkl'
    val_metadata: 'val_metadata.pkl'
    test_metadata: 'test_metadata.pkl'
    clip_length_in_frames: 20
    frames_between_clips: 1
    frame_rate: 5  # re-sample framerate, total of clip_length_in_frames*frame_rate frames covered
    train_split: 0.8
    batch_size: 1
    num_workers: 4
    random_state: 42
model:
    backbone: {
        'module': 'r2plus1d', 
        'function': {
            'name': 'create_r2plus1d',
            'kwargs': {}
        }
    }
    lr: 1.e-4
    betas: [0.9, 0.999]
    log_n_steps: 50
    recall_horizon: 13  # = recall_horizon + preview_horizon == clip_length_in_frames, recall_horizon at least 13
    preview_horizon: 7  #
