experiment: 'predictive_horizon'
lightning_module: 'PredictiveHorizonModule'
lightning_data_module: 'ImageSequenceDataModule'
model_checkpoint: 
    monitor: 'val/distance'
    mode: 'min'
trainer:
    gpus: 1
    max_epochs: 20
    log_every_n_steps: 1
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    fast_dev_run: False
    profiler: False
data:
    pkl_name: 'log.pkl'
    pkl_path: 'cholec80_frames'
    train_split: 0.8
    batch_size: 1
    num_workers: 4
    random_state: 42
    tolerance: 0.2 # change this tolerance
    seq_len: 20
    frame_increment: 1
    train_transforms: null
    val_transforms: null
    test_transforms: null
model:
    backbone: {
        'module': 'r2plus1d', 
        'function': {
            'name': 'create_r2plus1d',
            'kwargs': {}
        }
    }
    lr: 1.e-1
    betas: [0.9, 0.999]
    log_n_steps: 30
    recall_horizon: 15  # = recall_horizon + preview_horizon == clip_length_in_frames, recall_horizon at least 13
    preview_horizon: 10  #
