databases:
- name: cholec80
  prefix: cholec80
  test: false
  transforms: [
    ['Crop': {'top_left_corner': [65, 110], 'shape': [386, 624]}, 'Resize': {'dsize': [740, 555]}]
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}],
  #   ['Crop': {'top_left_corner': [], 'shape': []}, 'Resize': {'dsize': [720, 540]}]
  ]
  videos: 
    files: [
      'video01.mp4'
      # 'video02.mp4',
      # 'video03.mp4',
      # 'video04.mp4',
      # 'video05.mp4',
      # 'video06.mp4',
      # 'video07.mp4',
      # 'video08.mp4',
      # 'video09.mp4',
      # 'video10.mp4',
      # 'video11.mp4',
      # 'video12.mp4',
      # 'video13.mp4',
      # 'video14.mp4',
      # 'video15.mp4',
      # 'video16.mp4',
      # 'video17.mp4',
      # 'video18.mp4',
      # 'video19.mp4',
      # 'video20.mp4',
      # 'video21.mp4',
      # 'video22.mp4',
      # 'video23.mp4',
      # 'video24.mp4',
      # 'video25.mp4',
      # 'video26.mp4',
      # 'video27.mp4',
      # 'video28.mp4',
      # 'video29.mp4',
      # 'video30.mp4',
      # 'video31.mp4',
      # 'video32.mp4',
      # 'video33.mp4',
      # 'video34.mp4',
      # 'video35.mp4',
      # 'video36.mp4',
      # 'video37.mp4',
      # 'video38.mp4',
      # 'video39.mp4',
      # 'video40.mp4',
      # 'video41.mp4',
      # 'video42.mp4',
      # 'video43.mp4',
      # 'video44.mp4',
      # 'video45.mp4',
      # 'video46.mp4',
      # 'video47.mp4',
      # 'video48.mp4',
      # 'video49.mp4',
      # 'video50.mp4',
      # 'video51.mp4',
      # 'video52.mp4',
      # 'video53.mp4',
      # 'video54.mp4',
      # 'video55.mp4',
      # 'video56.mp4',
      # 'video57.mp4',
      # 'video58.mp4',
      # 'video59.mp4',
      # 'video60.mp4',
      # 'video61.mp4',
      # 'video62.mp4',
      # 'video63.mp4',
      # 'video64.mp4',
      # 'video65.mp4',
      # 'video66.mp4',
      # 'video67.mp4',
      # 'video68.mp4',
      # 'video69.mp4',
      # 'video70.mp4',
      # 'video71.mp4',
      # 'video72.mp4',
      # 'video73.mp4',
      # 'video74.mp4',
      # 'video75.mp4',
      # 'video76.mp4',
      # 'video77.mp4',
      # 'video78.mp4',
      # 'video79.mp4',
      # 'video80.mp4'
    ]
    prefix: videos
