experiment: 'deep_image_homography_estimation'
lightning_module: 'DeepImageHomographyEstimationModule'
trainer:
    gpus: 1
    max_epochs: 10
    limit_train_batches: 0.001
    limit_val_batches: 0.001
    limit_test_batches: 0.001
data:
    pkl_name: 'log_without_camera_motion_seq_len_2.pkl'
    pkl_path: 'camera_motion_separated_png/without_camera_motion'
    train_split: 0.8
    batch_size: 2
    num_workers: 2
    rho: 32
    crp_shape: [120, 160]
hparams:
    lr: 1.e-4
    betas: [0.9, 0.999]
