experiment: 'feature_lstm'
lightning_module: 'FeatureLSTMModule'
lightning_data_module: 'ImageSequenceDataModule'
trainer:
    gpus: 1
    max_epochs: 20
    log_every_n_steps: 100
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
data:
    pkl_name: 'log_with_camera_motion_seq_len_20.pkl'
    pkl_path: 'camera_motion_separated_png/with_camera_motion'
    train_split: 0.8
    random_state: 42
    batch_size: 16
    num_workers: 4
    train_transforms: null
    val_transforms: null
model:
    shape: [3, 480, 640]
    lr: 1.e-4
    betas: [0.9, 0.999]
    log_n_steps: 1000
