{
'SurgVisDom_test_no_indicators': {
      'type1': ['Crop': {'top_left_corner': [18, 164], 'shape': [506, 632]}, 'Resize': {'dsize': [740, 555]}],
      'type2': ['Crop': {'top_left_corner': [18,  29], 'shape': [506, 899]}, 'Resize': {'dsize': [740, 555]}]
    },
'SurgVisDom_test_indicators': {
  'default':                      ['Crop': {'top_left_corner': [ 64, 163], 'shape': [424, 632]}, 'Resize': {'dsize': [740, 555]}],
  'bs indicator':                 ['Crop': {'top_left_corner': [ 64, 163], 'shape': [404, 632]}, 'Resize': {'dsize': [740, 555]}],
  'rhs indicator':                ['Crop': {'top_left_corner': [ 64, 163], 'shape': [426, 591]}, 'Resize': {'dsize': [740, 555]}],
  'rhs indicator, bs indicator':  ['Crop': {'top_left_corner': [ 64, 163], 'shape': [404, 591]}, 'Resize': {'dsize': [740, 555]}],
  'lhs indicator, rhs indicator': ['Crop': {'top_left_corner': [ 64, 204], 'shape': [424, 550]}, 'Resize': {'dsize': [740, 555]}],
  'obstruction':                  ['Crop': {'top_left_corner': [160, 260], 'shape': [328, 535]}, 'Resize': {'dsize': [740, 555]}],
},
'SurgVisDom_train_indicators': {
  'default':                          ['Crop': {'top_left_corner': [64, 163], 'shape': [424, 632]}, 'Resize': {'dsize': [740, 555]}],
  'bs indicator':                     ['Crop': {'top_left_corner': [64, 163], 'shape': [404, 632]}, 'Resize': {'dsize': [740, 555]}],
  'big bs indicator':                 ['Crop': {'top_left_corner': [64, 163], 'shape': [348, 632]}, 'Resize': {'dsize': [740, 555]}],
  'tlhs indicator':                   ['Crop': {'top_left_corner': [80, 163], 'shape': [408, 632]}, 'Resize': {'dsize': [740, 555]}],
  'big bs indicator, tlhs indicator': ['Crop': {'top_left_corner': [80, 163], 'shape': [332, 632]}, 'Resize': {'dsize': [740, 555]}],
  'lhs indicator':                    ['Crop': {'top_left_corner': [64, 204], 'shape': [424, 591]}, 'Resize': {'dsize': [740, 555]}],
  'rhs indicator':                    ['Crop': {'top_left_corner': [64, 163], 'shape': [424, 591]}, 'Resize': {'dsize': [740, 555]}],
  'lhs indicator, bs indicator':      ['Crop': {'top_left_corner': [64, 204], 'shape': [404, 591]}, 'Resize': {'dsize': [740, 555]}],
  'rhs indicator, bs indicator':      ['Crop': {'top_left_corner': [64, 163], 'shape': [404, 591]}, 'Resize': {'dsize': [740, 555]}],
  'lhs indicator, rhs indicator':     ['Crop': {'top_left_corner': [64, 204], 'shape': [424, 550]}, 'Resize': {'dsize': [740, 555]}]
},
'Mountney': {
  'default': ['Crop': {'top_left_corner': [0, 9], 'shape': [480, 631]}, 'Resize': {'dsize': [740, 555]}]
},
'Giannarou': {
  'default': ['Crop': {'top_left_corner': [0, 9], 'shape': [480, 631]}, 'Resize': {'dsize': [740, 555]}]
}
}
