databases:
- name: SurgVisDom_test_no_indicators_with_camera_motion
  prefix: /media/martin/Samsung_T5/data/endoscopic_data/camera_motion_separated
  transforms:
  - &id001
    - Crop:
        shape:
        - 506
        - 632
        top_left_corner:
        - 18
        - 164
    - Resize:
        dsize:
        - 720
        - 540
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  - &id002
    - Crop:
        shape:
        - 506
        - 899
        top_left_corner:
        - 18
        - 29
    - Resize:
        dsize:
        - 720
        - 540
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id001
  - *id001
  - *id001
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  videos:
  - with_camera_motion/test/vid_0.mp4
  - with_camera_motion/train/vid_1.mp4
  - with_camera_motion/train/vid_2.mp4
  - with_camera_motion/train/vid_3.mp4
  - with_camera_motion/test/vid_4.mp4
  - with_camera_motion/train/vid_5.mp4
  - with_camera_motion/train/vid_6.mp4
  - with_camera_motion/train/vid_7.mp4
  - with_camera_motion/test/vid_8.mp4
  - with_camera_motion/train/vid_9.mp4
  - with_camera_motion/train/vid_10.mp4
  - with_camera_motion/test/vid_11.mp4
  - with_camera_motion/train/vid_12.mp4
  - with_camera_motion/train/vid_13.mp4
  - with_camera_motion/train/vid_14.mp4
  - with_camera_motion/test/vid_15.mp4
  - with_camera_motion/train/vid_16.mp4
  - with_camera_motion/train/vid_17.mp4
  - with_camera_motion/train/vid_18.mp4
  - with_camera_motion/test/vid_19.mp4
  - with_camera_motion/train/vid_20.mp4
  - with_camera_motion/train/vid_21.mp4
  - with_camera_motion/train/vid_22.mp4
  - with_camera_motion/train/vid_23.mp4
  - with_camera_motion/test/vid_24.mp4
  - with_camera_motion/train/vid_25.mp4
  - with_camera_motion/train/vid_26.mp4
  - with_camera_motion/train/vid_27.mp4
  - with_camera_motion/train/vid_28.mp4
  - with_camera_motion/train/vid_29.mp4
  - with_camera_motion/train/vid_30.mp4
  - with_camera_motion/train/vid_31.mp4
  - with_camera_motion/test/vid_32.mp4
  - with_camera_motion/train/vid_33.mp4
  - with_camera_motion/train/vid_34.mp4
  - with_camera_motion/test/vid_35.mp4
  - with_camera_motion/train/vid_36.mp4
  - with_camera_motion/train/vid_37.mp4
  - with_camera_motion/train/vid_38.mp4
  - with_camera_motion/train/vid_39.mp4
  - with_camera_motion/test/vid_40.mp4
  - with_camera_motion/train/vid_41.mp4
  - with_camera_motion/train/vid_42.mp4
  - with_camera_motion/train/vid_43.mp4
  - with_camera_motion/train/vid_44.mp4
  - with_camera_motion/test/vid_45.mp4
  - with_camera_motion/train/vid_46.mp4
  - with_camera_motion/train/vid_47.mp4
  - with_camera_motion/train/vid_48.mp4
  - with_camera_motion/test/vid_49.mp4
  - with_camera_motion/train/vid_50.mp4
  - with_camera_motion/train/vid_51.mp4
  - with_camera_motion/train/vid_52.mp4
  - with_camera_motion/train/vid_53.mp4
  - with_camera_motion/train/vid_54.mp4
  - with_camera_motion/train/vid_55.mp4
  - with_camera_motion/train/vid_56.mp4
  - with_camera_motion/train/vid_57.mp4
  - with_camera_motion/test/vid_58.mp4
  - with_camera_motion/train/vid_59.mp4
  - with_camera_motion/train/vid_60.mp4
  - with_camera_motion/train/vid_61.mp4
  - with_camera_motion/test/vid_62.mp4
  - with_camera_motion/train/vid_63.mp4
  - with_camera_motion/train/vid_64.mp4
  - with_camera_motion/train/vid_65.mp4
  - with_camera_motion/train/vid_66.mp4
  - with_camera_motion/train/vid_67.mp4
  - with_camera_motion/test/vid_68.mp4
  - with_camera_motion/train/vid_69.mp4
  - with_camera_motion/train/vid_70.mp4
  - with_camera_motion/train/vid_71.mp4
  - with_camera_motion/train/vid_72.mp4
  - with_camera_motion/train/vid_73.mp4
  - with_camera_motion/train/vid_74.mp4
  - with_camera_motion/test/vid_75.mp4
  - with_camera_motion/train/vid_76.mp4
  - with_camera_motion/train/vid_77.mp4
  - with_camera_motion/train/vid_78.mp4
  - with_camera_motion/train/vid_79.mp4
  - with_camera_motion/train/vid_80.mp4
  - with_camera_motion/test/vid_81.mp4
  - with_camera_motion/train/vid_82.mp4
  - with_camera_motion/train/vid_83.mp4
  - with_camera_motion/train/vid_84.mp4
  - with_camera_motion/train/vid_85.mp4
  - with_camera_motion/train/vid_86.mp4
  - with_camera_motion/train/vid_87.mp4
  - with_camera_motion/train/vid_88.mp4
  - with_camera_motion/train/vid_89.mp4
  - with_camera_motion/train/vid_90.mp4
  - with_camera_motion/train/vid_91.mp4
  - with_camera_motion/test/vid_92.mp4
  - with_camera_motion/train/vid_93.mp4
  - with_camera_motion/train/vid_94.mp4
  - with_camera_motion/train/vid_95.mp4
  - with_camera_motion/train/vid_96.mp4
  - with_camera_motion/test/vid_97.mp4
  - with_camera_motion/train/vid_98.mp4
  - with_camera_motion/train/vid_99.mp4
  - with_camera_motion/train/vid_100.mp4
  - with_camera_motion/test/vid_101.mp4
  - with_camera_motion/train/vid_102.mp4
  - with_camera_motion/train/vid_103.mp4
  - with_camera_motion/train/vid_104.mp4
  - with_camera_motion/train/vid_105.mp4
  - with_camera_motion/train/vid_106.mp4
  - with_camera_motion/test/vid_107.mp4
  - with_camera_motion/train/vid_108.mp4
  - with_camera_motion/train/vid_109.mp4
  - with_camera_motion/test/vid_110.mp4
  - with_camera_motion/train/vid_111.mp4
  - with_camera_motion/train/vid_112.mp4
  - with_camera_motion/test/vid_113.mp4
  - with_camera_motion/train/vid_114.mp4
  - with_camera_motion/test/vid_115.mp4
  - with_camera_motion/train/vid_116.mp4
  - with_camera_motion/train/vid_117.mp4
- name: SurgVisDom_test_indicators_with_camera_motion
  prefix: /media/martin/Samsung_T5/data/endoscopic_data/camera_motion_separated
  transforms:
  - &id003
    - Crop:
        shape:
        - 404
        - 632
        top_left_corner:
        - 64
        - 163
    - Resize:
        dsize:
        - 720
        - 540
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - - Crop:
        shape:
        - 404
        - 591
        top_left_corner:
        - 64
        - 163
    - Resize:
        dsize:
        - 720
        - 540
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  videos:
  - with_camera_motion/test/vid_118.mp4
  - with_camera_motion/train/vid_119.mp4
  - with_camera_motion/train/vid_120.mp4
  - with_camera_motion/train/vid_121.mp4
  - with_camera_motion/test/vid_122.mp4
  - with_camera_motion/train/vid_123.mp4
  - with_camera_motion/train/vid_124.mp4
  - with_camera_motion/train/vid_125.mp4
  - with_camera_motion/train/vid_126.mp4
  - with_camera_motion/train/vid_127.mp4
  - with_camera_motion/train/vid_128.mp4
  - with_camera_motion/train/vid_129.mp4
  - with_camera_motion/train/vid_130.mp4
  - with_camera_motion/train/vid_131.mp4
  - with_camera_motion/test/vid_132.mp4
  - with_camera_motion/train/vid_133.mp4
  - with_camera_motion/train/vid_134.mp4
  - with_camera_motion/test/vid_135.mp4
  - with_camera_motion/train/vid_136.mp4
  - with_camera_motion/train/vid_137.mp4
  - with_camera_motion/test/vid_138.mp4
  - with_camera_motion/train/vid_139.mp4
  - with_camera_motion/train/vid_140.mp4
  - with_camera_motion/test/vid_141.mp4
  - with_camera_motion/train/vid_142.mp4
  - with_camera_motion/train/vid_143.mp4
  - with_camera_motion/train/vid_144.mp4
  - with_camera_motion/train/vid_145.mp4
  - with_camera_motion/test/vid_146.mp4
  - with_camera_motion/train/vid_147.mp4
  - with_camera_motion/train/vid_148.mp4
  - with_camera_motion/train/vid_149.mp4
  - with_camera_motion/train/vid_150.mp4
  - with_camera_motion/test/vid_151.mp4
  - with_camera_motion/test/vid_152.mp4
  - with_camera_motion/train/vid_153.mp4
  - with_camera_motion/train/vid_154.mp4
- name: SurgVisDom_train_indicators_with_camera_motion
  prefix: /media/martin/Samsung_T5/data/endoscopic_data/camera_motion_separated
  transforms:
  - &id004
    - Crop:
        shape:
        - 404
        - 632
        top_left_corner:
        - 64
        - 163
    - Resize:
        dsize:
        - 720
        - 540
  - *id004
  - *id004
  - *id004
  - *id004
  - *id004
  - &id005
    - Crop:
        shape:
        - 404
        - 591
        top_left_corner:
        - 64
        - 163
    - Resize:
        dsize:
        - 720
        - 540
  - *id004
  - *id004
  - *id005
  - *id004
  - *id005
  - *id004
  - *id005
  - *id004
  - *id005
  - *id004
  - - Crop:
        shape:
        - 404
        - 591
        top_left_corner:
        - 64
        - 204
    - Resize:
        dsize:
        - 720
        - 540
  - &id006
    - Crop:
        shape:
        - 332
        - 632
        top_left_corner:
        - 80
        - 163
    - Resize:
        dsize:
        - 720
        - 540
  - *id006
  - *id006
  - *id006
  - *id004
  - *id004
  - *id004
  - *id004
  - *id004
  - *id004
  - *id004
  videos:
  - with_camera_motion/train/vid_155.mp4
  - with_camera_motion/test/vid_156.mp4
  - with_camera_motion/train/vid_157.mp4
  - with_camera_motion/train/vid_158.mp4
  - with_camera_motion/train/vid_159.mp4
  - with_camera_motion/test/vid_160.mp4
  - with_camera_motion/train/vid_161.mp4
  - with_camera_motion/train/vid_162.mp4
  - with_camera_motion/train/vid_163.mp4
  - with_camera_motion/test/vid_164.mp4
  - with_camera_motion/train/vid_165.mp4
  - with_camera_motion/test/vid_166.mp4
  - with_camera_motion/train/vid_167.mp4
  - with_camera_motion/train/vid_168.mp4
  - with_camera_motion/train/vid_169.mp4
  - with_camera_motion/train/vid_170.mp4
  - with_camera_motion/train/vid_171.mp4
  - with_camera_motion/test/vid_172.mp4
  - with_camera_motion/train/vid_173.mp4
  - with_camera_motion/train/vid_174.mp4
  - with_camera_motion/test/vid_175.mp4
  - with_camera_motion/train/vid_176.mp4
  - with_camera_motion/test/vid_177.mp4
  - with_camera_motion/train/vid_178.mp4
  - with_camera_motion/test/vid_179.mp4
  - with_camera_motion/train/vid_180.mp4
  - with_camera_motion/train/vid_181.mp4
  - with_camera_motion/train/vid_182.mp4
  - with_camera_motion/test/vid_183.mp4
- name: Mountney_with_camera_motion
  prefix: /media/martin/Samsung_T5/data/endoscopic_data/camera_motion_separated
  transforms:
  - &id007
    - Crop:
        shape:
        - 480
        - 631
        top_left_corner:
        - 0
        - 9
    - Resize:
        dsize:
        - 720
        - 540
  - *id007
  - *id007
  - *id007
  - *id007
  videos:
  - with_camera_motion/train/vid_184.avi
  - with_camera_motion/train/vid_185.avi
  - with_camera_motion/train/vid_186.avi
  - with_camera_motion/test/vid_187.avi
  - with_camera_motion/train/vid_188.avi
- name: Giannarou_with_camera_motion
  prefix: /media/martin/Samsung_T5/data/endoscopic_data/camera_motion_separated
  transforms:
  - - Crop:
        shape:
        - 480
        - 631
        top_left_corner:
        - 0
        - 9
    - Resize:
        dsize:
        - 720
        - 540
  videos:
  - with_camera_motion/test/vid_189.avi
