databases:
- name: SurgVisDom_test_no_indicators_with_camera_motion
  prefix: /media/martin/Samsung_T5/data/endoscopic_data/camera_motion_separated
  test: false
  transforms:
  - &id001
    - Crop:
        shape:
        - 506
        - 632
        top_left_corner:
        - 18
        - 164
    - Resize:
        dsize:
        - 740
        - 555
  - *id001
  - *id001
  - *id001
  - &id002
    - Crop:
        shape:
        - 506
        - 899
        top_left_corner:
        - 18
        - 29
    - Resize:
        dsize:
        - 740
        - 555
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id001
  - *id001
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  videos:
    files:
    - vid_1.mp4
    - vid_2.mp4
    - vid_3.mp4
    - vid_5.mp4
    - vid_6.mp4
    - vid_7.mp4
    - vid_9.mp4
    - vid_10.mp4
    - vid_12.mp4
    - vid_13.mp4
    - vid_14.mp4
    - vid_16.mp4
    - vid_17.mp4
    - vid_18.mp4
    - vid_20.mp4
    - vid_21.mp4
    - vid_22.mp4
    - vid_23.mp4
    - vid_25.mp4
    - vid_26.mp4
    - vid_27.mp4
    - vid_28.mp4
    - vid_29.mp4
    - vid_30.mp4
    - vid_31.mp4
    - vid_33.mp4
    - vid_34.mp4
    - vid_36.mp4
    - vid_37.mp4
    - vid_38.mp4
    - vid_39.mp4
    - vid_41.mp4
    - vid_42.mp4
    - vid_43.mp4
    - vid_44.mp4
    - vid_46.mp4
    - vid_47.mp4
    - vid_48.mp4
    - vid_50.mp4
    - vid_51.mp4
    - vid_52.mp4
    - vid_53.mp4
    - vid_54.mp4
    - vid_55.mp4
    - vid_56.mp4
    - vid_57.mp4
    - vid_59.mp4
    - vid_60.mp4
    - vid_61.mp4
    - vid_63.mp4
    - vid_64.mp4
    - vid_65.mp4
    - vid_66.mp4
    - vid_67.mp4
    - vid_69.mp4
    - vid_70.mp4
    - vid_71.mp4
    - vid_72.mp4
    - vid_73.mp4
    - vid_74.mp4
    - vid_76.mp4
    - vid_77.mp4
    - vid_78.mp4
    - vid_79.mp4
    - vid_80.mp4
    - vid_82.mp4
    - vid_83.mp4
    - vid_84.mp4
    - vid_85.mp4
    - vid_86.mp4
    - vid_87.mp4
    - vid_88.mp4
    - vid_89.mp4
    - vid_90.mp4
    - vid_91.mp4
    - vid_93.mp4
    - vid_94.mp4
    - vid_95.mp4
    - vid_96.mp4
    - vid_98.mp4
    - vid_99.mp4
    - vid_100.mp4
    - vid_102.mp4
    - vid_103.mp4
    - vid_104.mp4
    - vid_105.mp4
    - vid_106.mp4
    - vid_108.mp4
    - vid_109.mp4
    - vid_111.mp4
    - vid_112.mp4
    - vid_114.mp4
    - vid_116.mp4
    - vid_117.mp4
    prefix: with_camera_motion/train
- name: SurgVisDom_test_no_indicators_with_camera_motion
  prefix: /media/martin/Samsung_T5/data/endoscopic_data/camera_motion_separated
  test: true
  transforms:
  - *id001
  - *id001
  - *id002
  - *id002
  - *id002
  - *id001
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id001
  - *id001
  - *id001
  videos:
    files:
    - vid_0.mp4
    - vid_4.mp4
    - vid_8.mp4
    - vid_11.mp4
    - vid_15.mp4
    - vid_19.mp4
    - vid_24.mp4
    - vid_32.mp4
    - vid_35.mp4
    - vid_40.mp4
    - vid_45.mp4
    - vid_49.mp4
    - vid_58.mp4
    - vid_62.mp4
    - vid_68.mp4
    - vid_75.mp4
    - vid_81.mp4
    - vid_92.mp4
    - vid_97.mp4
    - vid_101.mp4
    - vid_107.mp4
    - vid_110.mp4
    - vid_113.mp4
    - vid_115.mp4
    prefix: with_camera_motion/test
- name: SurgVisDom_test_indicators_with_camera_motion
  prefix: /media/martin/Samsung_T5/data/endoscopic_data/camera_motion_separated
  test: false
  transforms:
  - &id003
    - Crop:
        shape:
        - 404
        - 632
        top_left_corner:
        - 64
        - 163
    - Resize:
        dsize:
        - 740
        - 555
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - - Crop:
        shape:
        - 404
        - 591
        top_left_corner:
        - 64
        - 163
    - Resize:
        dsize:
        - 740
        - 555
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  videos:
    files:
    - vid_119.mp4
    - vid_120.mp4
    - vid_121.mp4
    - vid_123.mp4
    - vid_124.mp4
    - vid_125.mp4
    - vid_126.mp4
    - vid_127.mp4
    - vid_128.mp4
    - vid_129.mp4
    - vid_130.mp4
    - vid_131.mp4
    - vid_133.mp4
    - vid_134.mp4
    - vid_136.mp4
    - vid_137.mp4
    - vid_139.mp4
    - vid_140.mp4
    - vid_142.mp4
    - vid_143.mp4
    - vid_144.mp4
    - vid_145.mp4
    - vid_147.mp4
    - vid_148.mp4
    - vid_149.mp4
    - vid_150.mp4
    - vid_153.mp4
    - vid_154.mp4
    prefix: with_camera_motion/train
- name: SurgVisDom_test_indicators_with_camera_motion
  prefix: /media/martin/Samsung_T5/data/endoscopic_data/camera_motion_separated
  test: true
  transforms:
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  videos:
    files:
    - vid_118.mp4
    - vid_122.mp4
    - vid_132.mp4
    - vid_135.mp4
    - vid_138.mp4
    - vid_141.mp4
    - vid_146.mp4
    - vid_151.mp4
    - vid_152.mp4
    prefix: with_camera_motion/test
- name: SurgVisDom_train_indicators_with_camera_motion
  prefix: /media/martin/Samsung_T5/data/endoscopic_data/camera_motion_separated
  test: false
  transforms:
  - &id004
    - Crop:
        shape:
        - 404
        - 632
        top_left_corner:
        - 64
        - 163
    - Resize:
        dsize:
        - 740
        - 555
  - *id004
  - *id004
  - *id004
  - &id005
    - Crop:
        shape:
        - 404
        - 591
        top_left_corner:
        - 64
        - 163
    - Resize:
        dsize:
        - 740
        - 555
  - *id004
  - *id004
  - *id004
  - *id004
  - *id005
  - *id004
  - *id005
  - *id004
  - &id006
    - Crop:
        shape:
        - 332
        - 632
        top_left_corner:
        - 80
        - 163
    - Resize:
        dsize:
        - 740
        - 555
  - *id006
  - *id006
  - *id004
  - *id004
  - *id004
  - *id004
  videos:
    files:
    - vid_155.mp4
    - vid_157.mp4
    - vid_158.mp4
    - vid_159.mp4
    - vid_161.mp4
    - vid_162.mp4
    - vid_163.mp4
    - vid_165.mp4
    - vid_167.mp4
    - vid_168.mp4
    - vid_169.mp4
    - vid_170.mp4
    - vid_171.mp4
    - vid_173.mp4
    - vid_174.mp4
    - vid_176.mp4
    - vid_178.mp4
    - vid_180.mp4
    - vid_181.mp4
    - vid_182.mp4
    prefix: with_camera_motion/train
- name: SurgVisDom_train_indicators_with_camera_motion
  prefix: /media/martin/Samsung_T5/data/endoscopic_data/camera_motion_separated
  test: true
  transforms:
  - *id004
  - *id004
  - *id005
  - *id005
  - - Crop:
        shape:
        - 404
        - 591
        top_left_corner:
        - 64
        - 204
    - Resize:
        dsize:
        - 740
        - 555
  - *id006
  - *id004
  - *id004
  - *id004
  videos:
    files:
    - vid_156.mp4
    - vid_160.mp4
    - vid_164.mp4
    - vid_166.mp4
    - vid_172.mp4
    - vid_175.mp4
    - vid_177.mp4
    - vid_179.mp4
    - vid_183.mp4
    prefix: with_camera_motion/test
- name: Mountney_with_camera_motion
  prefix: /media/martin/Samsung_T5/data/endoscopic_data/camera_motion_separated
  test: false
  transforms:
  - &id007
    - Crop:
        shape:
        - 480
        - 631
        top_left_corner:
        - 0
        - 9
    - Resize:
        dsize:
        - 740
        - 555
  - *id007
  - *id007
  - *id007
  videos:
    files:
    - vid_184.avi
    - vid_185.avi
    - vid_186.avi
    - vid_188.avi
    prefix: with_camera_motion/train
- name: Mountney_with_camera_motion
  prefix: /media/martin/Samsung_T5/data/endoscopic_data/camera_motion_separated
  test: true
  transforms:
  - *id007
  videos:
    files:
    - vid_187.avi
    prefix: with_camera_motion/test
- name: Giannarou_with_camera_motion
  prefix: /media/martin/Samsung_T5/data/endoscopic_data/camera_motion_separated
  test: true
  transforms:
  - - Crop:
        shape:
        - 480
        - 631
        top_left_corner:
        - 0
        - 9
    - Resize:
        dsize:
        - 740
        - 555
  videos:
    files:
    - vid_189.avi
    prefix: with_camera_motion/test
