databases:
- name: SurgVisDom_test_no_indicators_without_camera_motion
  prefix: camera_motion_separated
  test: false
  transforms:
  - &id001
    - Crop:
        shape:
        - 506
        - 632
        top_left_corner:
        - 18
        - 164
    - Resize:
        dsize:
        - 816
        - 612
    - RandomEdgeHomography:
        rho: 64
        crp_shape:
        - 480
        - 640
        homography_return: 2
  - *id001
  - *id001
  - &id002
    - Crop:
        shape:
        - 506
        - 899
        top_left_corner:
        - 18
        - 29
    - Resize:
        dsize:
        - 816
        - 612
    - RandomEdgeHomography:
        rho: 64
        crp_shape:
        - 480
        - 640
        homography_return: 2
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id001
  - *id001
  - *id001
  - *id001
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  - *id002
  videos:
    files:
    - vid_4.mp4
    - vid_5.mp4
    - vid_6.mp4
    - vid_9.mp4
    - vid_10.mp4
    - vid_12.mp4
    - vid_13.mp4
    - vid_15.mp4
    - vid_16.mp4
    - vid_18.mp4
    - vid_20.mp4
    - vid_21.mp4
    - vid_22.mp4
    - vid_23.mp4
    - vid_24.mp4
    - vid_26.mp4
    - vid_28.mp4
    - vid_29.mp4
    - vid_31.mp4
    - vid_32.mp4
    - vid_34.mp4
    - vid_35.mp4
    - vid_37.mp4
    - vid_38.mp4
    - vid_39.mp4
    - vid_40.mp4
    - vid_42.mp4
    - vid_43.mp4
    - vid_44.mp4
    - vid_45.mp4
    - vid_47.mp4
    - vid_48.mp4
    - vid_49.mp4
    - vid_51.mp4
    - vid_52.mp4
    - vid_53.mp4
    - vid_54.mp4
    - vid_55.mp4
    - vid_56.mp4
    - vid_57.mp4
    - vid_58.mp4
    - vid_60.mp4
    - vid_61.mp4
    - vid_63.mp4
    - vid_64.mp4
    - vid_65.mp4
    - vid_67.mp4
    - vid_68.mp4
    - vid_69.mp4
    - vid_70.mp4
    - vid_71.mp4
    - vid_73.mp4
    - vid_74.mp4
    - vid_75.mp4
    - vid_76.mp4
    - vid_77.mp4
    - vid_78.mp4
    - vid_79.mp4
    - vid_80.mp4
    - vid_82.mp4
    - vid_83.mp4
    - vid_84.mp4
    - vid_85.mp4
    - vid_86.mp4
    - vid_88.mp4
    - vid_89.mp4
    - vid_90.mp4
    - vid_91.mp4
    - vid_92.mp4
    - vid_93.mp4
    - vid_94.mp4
    - vid_96.mp4
    - vid_97.mp4
    - vid_98.mp4
    - vid_99.mp4
    - vid_100.mp4
    - vid_101.mp4
    - vid_102.mp4
    - vid_104.mp4
    - vid_105.mp4
    - vid_107.mp4
    - vid_109.mp4
    - vid_110.mp4
    - vid_111.mp4
    - vid_112.mp4
    - vid_114.mp4
    - vid_115.mp4
    - vid_116.mp4
    - vid_117.mp4
    - vid_118.mp4
    - vid_120.mp4
    - vid_122.mp4
    - vid_123.mp4
    - vid_125.mp4
    - vid_126.mp4
    - vid_127.mp4
    prefix: without_camera_motion/train
- name: SurgVisDom_test_no_indicators_without_camera_motion
  prefix: camera_motion_separated
  test: true
  transforms:
  - *id001
  - *id001
  - *id001
  - *id001
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id001
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id002
  - *id001
  - *id001
  - *id001
  videos:
    files:
    - vid_0.mp4
    - vid_1.mp4
    - vid_2.mp4
    - vid_3.mp4
    - vid_7.mp4
    - vid_8.mp4
    - vid_11.mp4
    - vid_14.mp4
    - vid_17.mp4
    - vid_19.mp4
    - vid_25.mp4
    - vid_27.mp4
    - vid_30.mp4
    - vid_33.mp4
    - vid_36.mp4
    - vid_41.mp4
    - vid_46.mp4
    - vid_50.mp4
    - vid_59.mp4
    - vid_62.mp4
    - vid_66.mp4
    - vid_72.mp4
    - vid_81.mp4
    - vid_87.mp4
    - vid_95.mp4
    - vid_103.mp4
    - vid_106.mp4
    - vid_108.mp4
    - vid_113.mp4
    - vid_119.mp4
    - vid_121.mp4
    - vid_124.mp4
    prefix: without_camera_motion/test
- name: SurgVisDom_test_indicators_without_camera_motion
  prefix: camera_motion_separated
  test: false
  transforms:
  - &id003
    - Crop:
        shape:
        - 424
        - 632
        top_left_corner:
        - 64
        - 163
    - Resize:
        dsize:
        - 816
        - 612
    - RandomEdgeHomography:
        rho: 64
        crp_shape:
        - 480
        - 640
        homography_return: 2
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - &id005
    - Crop:
        shape:
        - 404
        - 632
        top_left_corner:
        - 64
        - 163
    - Resize:
        dsize:
        - 816
        - 612
    - RandomEdgeHomography:
        rho: 64
        crp_shape:
        - 480
        - 640
        homography_return: 2
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - &id007
    - Crop:
        shape:
        - 424
        - 550
        top_left_corner:
        - 64
        - 204
    - Resize:
        dsize:
        - 816
        - 612
    - RandomEdgeHomography:
        rho: 64
        crp_shape:
        - 480
        - 640
        homography_return: 2
  - *id003
  - - Crop:
        shape:
        - 328
        - 535
        top_left_corner:
        - 160
        - 260
    - Resize:
        dsize:
        - 816
        - 612
    - RandomEdgeHomography:
        rho: 64
        crp_shape:
        - 480
        - 640
        homography_return: 2
  - *id003
  - *id003
  - *id003
  - *id003
  - &id004
    - Crop:
        shape:
        - 426
        - 591
        top_left_corner:
        - 64
        - 163
    - Resize:
        dsize:
        - 816
        - 612
    - RandomEdgeHomography:
        rho: 64
        crp_shape:
        - 480
        - 640
        homography_return: 2
  - *id003
  - *id004
  - *id003
  - *id005
  - *id003
  - *id004
  - *id003
  - &id006
    - Crop:
        shape:
        - 404
        - 591
        top_left_corner:
        - 64
        - 163
    - Resize:
        dsize:
        - 816
        - 612
    - RandomEdgeHomography:
        rho: 64
        crp_shape:
        - 480
        - 640
        homography_return: 2
  - *id003
  - *id004
  - *id003
  - *id003
  - *id006
  - *id003
  - *id004
  - *id003
  - *id004
  - *id003
  - *id006
  - *id003
  - *id003
  - *id006
  - *id003
  - *id006
  - *id006
  - *id003
  - *id006
  - *id003
  - *id006
  - *id003
  - *id004
  - *id003
  - *id004
  - *id003
  - *id004
  - *id004
  - *id003
  - *id006
  - *id003
  - *id005
  - *id003
  - *id006
  - *id003
  - *id003
  - *id003
  - *id004
  - *id003
  - *id006
  - *id003
  - *id004
  - *id007
  - *id003
  - *id005
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id005
  - *id005
  - *id005
  - *id003
  - *id003
  - *id005
  - *id005
  - *id005
  - *id003
  - *id003
  - *id005
  - *id003
  - *id003
  - *id003
  - *id004
  - *id004
  - *id003
  - *id005
  - *id003
  - *id004
  - *id003
  - *id003
  - *id004
  - *id003
  - *id003
  - *id004
  - *id005
  - *id003
  - *id006
  - *id003
  - *id005
  - *id003
  - *id004
  - *id003
  - *id003
  - *id003
  - *id005
  - *id003
  - *id004
  - *id005
  - *id004
  - *id003
  - *id003
  - *id004
  - *id003
  - *id003
  - *id004
  - *id005
  - *id003
  - *id004
  - *id003
  - *id004
  - *id003
  - *id004
  - *id004
  - *id003
  - *id003
  - *id003
  - *id003
  - *id005
  - *id003
  - *id003
  - *id005
  - *id003
  - *id004
  - *id005
  videos:
    files:
    - vid_128.mp4
    - vid_131.mp4
    - vid_132.mp4
    - vid_133.mp4
    - vid_134.mp4
    - vid_135.mp4
    - vid_136.mp4
    - vid_138.mp4
    - vid_139.mp4
    - vid_140.mp4
    - vid_142.mp4
    - vid_143.mp4
    - vid_144.mp4
    - vid_145.mp4
    - vid_146.mp4
    - vid_147.mp4
    - vid_150.mp4
    - vid_152.mp4
    - vid_154.mp4
    - vid_155.mp4
    - vid_156.mp4
    - vid_158.mp4
    - vid_159.mp4
    - vid_160.mp4
    - vid_161.mp4
    - vid_162.mp4
    - vid_163.mp4
    - vid_166.mp4
    - vid_167.mp4
    - vid_168.mp4
    - vid_169.mp4
    - vid_170.mp4
    - vid_171.mp4
    - vid_173.mp4
    - vid_174.mp4
    - vid_175.mp4
    - vid_176.mp4
    - vid_177.mp4
    - vid_178.mp4
    - vid_179.mp4
    - vid_180.mp4
    - vid_181.mp4
    - vid_182.mp4
    - vid_183.mp4
    - vid_184.mp4
    - vid_185.mp4
    - vid_187.mp4
    - vid_188.mp4
    - vid_189.mp4
    - vid_190.mp4
    - vid_191.mp4
    - vid_192.mp4
    - vid_193.mp4
    - vid_195.mp4
    - vid_196.mp4
    - vid_197.mp4
    - vid_198.mp4
    - vid_200.mp4
    - vid_201.mp4
    - vid_202.mp4
    - vid_203.mp4
    - vid_206.mp4
    - vid_207.mp4
    - vid_208.mp4
    - vid_209.mp4
    - vid_210.mp4
    - vid_212.mp4
    - vid_213.mp4
    - vid_214.mp4
    - vid_215.mp4
    - vid_216.mp4
    - vid_217.mp4
    - vid_219.mp4
    - vid_220.mp4
    - vid_222.mp4
    - vid_223.mp4
    - vid_224.mp4
    - vid_226.mp4
    - vid_228.mp4
    - vid_230.mp4
    - vid_231.mp4
    - vid_233.mp4
    - vid_235.mp4
    - vid_236.mp4
    - vid_238.mp4
    - vid_239.mp4
    - vid_241.mp4
    - vid_243.mp4
    - vid_245.mp4
    - vid_247.mp4
    - vid_248.mp4
    - vid_249.mp4
    - vid_251.mp4
    - vid_252.mp4
    - vid_253.mp4
    - vid_255.mp4
    - vid_256.mp4
    - vid_257.mp4
    - vid_258.mp4
    - vid_259.mp4
    - vid_260.mp4
    - vid_261.mp4
    - vid_262.mp4
    - vid_263.mp4
    - vid_265.mp4
    - vid_266.mp4
    - vid_267.mp4
    - vid_268.mp4
    - vid_269.mp4
    - vid_270.mp4
    - vid_271.mp4
    - vid_272.mp4
    - vid_273.mp4
    - vid_274.mp4
    - vid_275.mp4
    - vid_277.mp4
    - vid_278.mp4
    - vid_279.mp4
    - vid_280.mp4
    - vid_281.mp4
    - vid_282.mp4
    - vid_283.mp4
    - vid_285.mp4
    - vid_286.mp4
    - vid_287.mp4
    - vid_289.mp4
    - vid_290.mp4
    - vid_291.mp4
    - vid_292.mp4
    - vid_293.mp4
    - vid_294.mp4
    - vid_295.mp4
    - vid_296.mp4
    - vid_297.mp4
    - vid_299.mp4
    - vid_300.mp4
    - vid_302.mp4
    - vid_303.mp4
    - vid_305.mp4
    - vid_306.mp4
    - vid_307.mp4
    - vid_309.mp4
    - vid_310.mp4
    - vid_311.mp4
    - vid_312.mp4
    - vid_313.mp4
    prefix: without_camera_motion/train
- name: SurgVisDom_test_indicators_without_camera_motion
  prefix: camera_motion_separated
  test: true
  transforms:
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id006
  - *id003
  - *id005
  - *id003
  - *id003
  - *id003
  - *id004
  - *id003
  - *id003
  - *id003
  - *id003
  - *id005
  - *id005
  - *id005
  - *id003
  - *id003
  - *id005
  - *id003
  - *id003
  - *id003
  - *id005
  - *id005
  - *id003
  - *id005
  - *id006
  - *id004
  - *id005
  - *id003
  - *id004
  - *id004
  - *id005
  - *id003
  videos:
    files:
    - vid_129.mp4
    - vid_130.mp4
    - vid_137.mp4
    - vid_141.mp4
    - vid_148.mp4
    - vid_149.mp4
    - vid_151.mp4
    - vid_153.mp4
    - vid_157.mp4
    - vid_164.mp4
    - vid_165.mp4
    - vid_172.mp4
    - vid_186.mp4
    - vid_194.mp4
    - vid_199.mp4
    - vid_204.mp4
    - vid_205.mp4
    - vid_211.mp4
    - vid_218.mp4
    - vid_221.mp4
    - vid_225.mp4
    - vid_227.mp4
    - vid_229.mp4
    - vid_232.mp4
    - vid_234.mp4
    - vid_237.mp4
    - vid_240.mp4
    - vid_242.mp4
    - vid_244.mp4
    - vid_246.mp4
    - vid_250.mp4
    - vid_254.mp4
    - vid_264.mp4
    - vid_276.mp4
    - vid_284.mp4
    - vid_288.mp4
    - vid_298.mp4
    - vid_301.mp4
    - vid_304.mp4
    - vid_308.mp4
    - vid_314.mp4
    prefix: without_camera_motion/test
- name: SurgVisDom_train_indicators_without_camera_motion
  prefix: camera_motion_separated
  test: false
  transforms:
  - &id008
    - Crop:
        shape:
        - 424
        - 632
        top_left_corner:
        - 64
        - 163
    - Resize:
        dsize:
        - 816
        - 612
    - RandomEdgeHomography:
        rho: 64
        crp_shape:
        - 480
        - 640
        homography_return: 2
  - &id011
    - Crop:
        shape:
        - 404
        - 632
        top_left_corner:
        - 64
        - 163
    - Resize:
        dsize:
        - 816
        - 612
    - RandomEdgeHomography:
        rho: 64
        crp_shape:
        - 480
        - 640
        homography_return: 2
  - *id008
  - *id008
  - &id009
    - Crop:
        shape:
        - 424
        - 591
        top_left_corner:
        - 64
        - 163
    - Resize:
        dsize:
        - 816
        - 612
    - RandomEdgeHomography:
        rho: 64
        crp_shape:
        - 480
        - 640
        homography_return: 2
  - *id008
  - *id009
  - *id008
  - *id009
  - *id008
  - *id009
  - *id008
  - *id009
  - *id008
  - *id009
  - *id008
  - *id009
  - *id009
  - *id008
  - *id009
  - *id009
  - *id008
  - *id009
  - *id008
  - *id009
  - *id008
  - *id008
  - *id008
  - *id009
  - *id008
  - *id008
  - *id008
  - *id008
  - *id009
  - *id008
  - *id009
  - *id009
  - *id008
  - *id009
  - *id008
  - *id008
  - *id008
  - *id008
  - *id009
  - *id008
  - *id009
  - *id008
  - *id008
  - *id008
  - *id009
  - *id009
  - *id008
  - *id008
  - *id008
  - *id009
  - *id008
  - *id008
  - *id008
  - *id008
  - *id009
  - *id008
  - *id009
  - *id009
  - *id008
  - *id009
  - *id008
  - *id008
  - *id008
  - - Crop:
        shape:
        - 424
        - 550
        top_left_corner:
        - 64
        - 204
    - Resize:
        dsize:
        - 816
        - 612
    - RandomEdgeHomography:
        rho: 64
        crp_shape:
        - 480
        - 640
        homography_return: 2
  - &id012
    - Crop:
        shape:
        - 424
        - 591
        top_left_corner:
        - 64
        - 204
    - Resize:
        dsize:
        - 816
        - 612
    - RandomEdgeHomography:
        rho: 64
        crp_shape:
        - 480
        - 640
        homography_return: 2
  - *id008
  - &id010
    - Crop:
        shape:
        - 408
        - 632
        top_left_corner:
        - 80
        - 163
    - Resize:
        dsize:
        - 816
        - 612
    - RandomEdgeHomography:
        rho: 64
        crp_shape:
        - 480
        - 640
        homography_return: 2
  - *id010
  - *id010
  - *id010
  - *id010
  - *id008
  - *id008
  - *id008
  - *id008
  - *id008
  - *id008
  - *id008
  - *id008
  - *id008
  - *id008
  - *id008
  - *id008
  - *id011
  - *id008
  - *id008
  - *id008
  videos:
    files:
    - vid_315.mp4
    - vid_316.mp4
    - vid_317.mp4
    - vid_319.mp4
    - vid_320.mp4
    - vid_321.mp4
    - vid_322.mp4
    - vid_323.mp4
    - vid_326.mp4
    - vid_327.mp4
    - vid_328.mp4
    - vid_329.mp4
    - vid_330.mp4
    - vid_331.mp4
    - vid_332.mp4
    - vid_333.mp4
    - vid_334.mp4
    - vid_336.mp4
    - vid_339.mp4
    - vid_340.mp4
    - vid_342.mp4
    - vid_343.mp4
    - vid_344.mp4
    - vid_345.mp4
    - vid_346.mp4
    - vid_347.mp4
    - vid_348.mp4
    - vid_350.mp4
    - vid_351.mp4
    - vid_352.mp4
    - vid_354.mp4
    - vid_355.mp4
    - vid_357.mp4
    - vid_358.mp4
    - vid_359.mp4
    - vid_360.mp4
    - vid_362.mp4
    - vid_363.mp4
    - vid_364.mp4
    - vid_365.mp4
    - vid_367.mp4
    - vid_369.mp4
    - vid_370.mp4
    - vid_372.mp4
    - vid_373.mp4
    - vid_374.mp4
    - vid_376.mp4
    - vid_378.mp4
    - vid_379.mp4
    - vid_380.mp4
    - vid_382.mp4
    - vid_383.mp4
    - vid_385.mp4
    - vid_386.mp4
    - vid_387.mp4
    - vid_388.mp4
    - vid_390.mp4
    - vid_391.mp4
    - vid_392.mp4
    - vid_393.mp4
    - vid_394.mp4
    - vid_395.mp4
    - vid_397.mp4
    - vid_398.mp4
    - vid_399.mp4
    - vid_400.mp4
    - vid_404.mp4
    - vid_406.mp4
    - vid_407.mp4
    - vid_408.mp4
    - vid_410.mp4
    - vid_411.mp4
    - vid_412.mp4
    - vid_413.mp4
    - vid_415.mp4
    - vid_416.mp4
    - vid_417.mp4
    - vid_418.mp4
    - vid_420.mp4
    - vid_421.mp4
    - vid_422.mp4
    - vid_424.mp4
    - vid_425.mp4
    - vid_428.mp4
    - vid_429.mp4
    - vid_430.mp4
    - vid_431.mp4
    - vid_433.mp4
    - vid_434.mp4
    - vid_435.mp4
    - vid_436.mp4
    - vid_437.mp4
    prefix: without_camera_motion/train
- name: SurgVisDom_train_indicators_without_camera_motion
  prefix: camera_motion_separated
  test: true
  transforms:
  - *id009
  - *id009
  - *id008
  - *id008
  - *id008
  - - Crop:
        shape:
        - 404
        - 591
        top_left_corner:
        - 64
        - 163
    - Resize:
        dsize:
        - 816
        - 612
    - RandomEdgeHomography:
        rho: 64
        crp_shape:
        - 480
        - 640
        homography_return: 2
  - *id008
  - *id009
  - *id009
  - *id009
  - *id008
  - *id009
  - *id009
  - *id008
  - *id008
  - *id009
  - *id008
  - *id009
  - *id008
  - *id008
  - *id009
  - *id008
  - *id009
  - *id009
  - *id012
  - *id010
  - *id008
  - *id008
  - *id011
  - *id012
  - *id008
  - *id008
  - *id008
  - *id008
  - *id008
  videos:
    files:
    - vid_318.mp4
    - vid_324.mp4
    - vid_325.mp4
    - vid_335.mp4
    - vid_337.mp4
    - vid_338.mp4
    - vid_341.mp4
    - vid_349.mp4
    - vid_353.mp4
    - vid_356.mp4
    - vid_361.mp4
    - vid_366.mp4
    - vid_368.mp4
    - vid_371.mp4
    - vid_375.mp4
    - vid_377.mp4
    - vid_381.mp4
    - vid_384.mp4
    - vid_389.mp4
    - vid_396.mp4
    - vid_401.mp4
    - vid_402.mp4
    - vid_403.mp4
    - vid_405.mp4
    - vid_409.mp4
    - vid_414.mp4
    - vid_419.mp4
    - vid_423.mp4
    - vid_426.mp4
    - vid_427.mp4
    - vid_432.mp4
    - vid_438.mp4
    - vid_439.mp4
    - vid_440.mp4
    - vid_441.mp4
    prefix: without_camera_motion/test
- name: Mountney_without_camera_motion
  prefix: camera_motion_separated
  test: false
  transforms:
  - &id013
    - Crop:
        shape:
        - 480
        - 631
        top_left_corner:
        - 0
        - 9
    - Resize:
        dsize:
        - 816
        - 612
    - RandomEdgeHomography:
        rho: 64
        crp_shape:
        - 480
        - 640
        homography_return: 2
  - *id013
  - *id013
  - *id013
  videos:
    files:
    - vid_442.avi
    - vid_443.avi
    - vid_444.avi
    - vid_446.avi
    prefix: without_camera_motion/train
- name: Mountney_without_camera_motion
  prefix: camera_motion_separated
  test: true
  transforms:
  - *id013
  videos:
    files:
    - vid_445.avi
    prefix: without_camera_motion/test
- name: Giannarou_without_camera_motion
  prefix: camera_motion_separated
  test: false
  transforms:
  - &id014
    - Crop:
        shape:
        - 480
        - 631
        top_left_corner:
        - 0
        - 9
    - Resize:
        dsize:
        - 816
        - 612
    - RandomEdgeHomography:
        rho: 64
        crp_shape:
        - 480
        - 640
        homography_return: 2
  videos:
    files:
    - vid_448.avi
    prefix: without_camera_motion/train
- name: Giannarou_without_camera_motion
  prefix: camera_motion_separated
  test: true
  transforms:
  - *id014
  videos:
    files:
    - vid_447.avi
    prefix: without_camera_motion/test
