experiment: 'predictive_horizon'
lightning_module: 'PredictiveHorizonModule'
lightning_data_module: 'VideoDataModule'
trainer:
    gpus: 1
    max_epochs: 20
    log_every_n_steps: 100
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
data:
    meta_df: 'cholec80_dummy_transforms.pkl'
    clip_length_in_frames: 25
    frames_between_clips: 1
    train_split: 0.8
    batch_size: 16
    num_workers: 4
    random_state: 42
model:
    shape: [3, 480, 640]
    lr: 1.e-4
    betas: [0.9, 0.999]
    log_n_steps: 1000
