experiment: 'unsupervised_deep_homography_estimation'
lightning_module: 'UnsupervisedDeepHomographyEstimationModule'
lightning_data_module: 'ConsecutiveDataModule'
trainer:
    gpus: 1
    max_epochs: 20
    log_every_n_steps: 1
    limit_train_batches: 0.001
    limit_val_batches: 0.002
    limit_test_batches: 0.001
data:
    pkl_name: 'log_without_camera_motion_seq_len_2.pkl'
    pkl_path: 'camera_motion_separated_png/without_camera_motion'
    train_split: 0.8
    batch_size: 32
    num_workers: 2
    rho: 8
    crp_shape: [128, 128]
    unsupervised: True
hparams:
    lr: 1.e-4
    betas: [0.9, 0.999]
