experiment: 'miccai/final/cholec80/resnet50'
lightning_module: 'ConvHomographyPredictorModule'
lightning_data_module: 'ImageSequenceMotionLabelDataModule'
trainer:
    accelerator: 'gpu'
    devices: 1
    max_epochs: 100
    log_every_n_steps: 100
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    fast_dev_run: False
    profiler: False
data:
    pkl_name: '23_03_07_motion_label_window_1_frame_increment_5_frames_between_clips_1_log_test_train.pkl'
    pkl_path: 'cholec80_single_video_frames_cropped'
    kwargs:
        train_split: 0.8
        batch_size: 64
        num_workers: 16
        random_state: 42
        tolerance: 0.2 # change this tolerance
        seq_len: 15
        frame_increment: 5
        frames_between_clips: 5 # seq_len*frame_increment
        random_frame_offset: True
        train_photometric_transforms:
            - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'MultiplyAndAddToBrightness', 'kwargs': {'mul': [0.5, 1.5], 'add': [30, 30]}}
            - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'Grayscale',                  'kwargs': {}}
            - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'ChangeColorTemperature',     'kwargs': {'kelvin': [3000, 15000]}}
            - {'chance': 0.2, 'module': 'imgaug.augmenters.imgcorruptlike', 'type': 'Contrast',                   'kwargs': {'severity': 1}}
            - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'AdditiveGaussianNoise',      'kwargs': {'scale': [0, 51]}}
            - {'chance': 0.2, 'module': 'imgaug.augmenters',                'type': 'GaussianBlur',               'kwargs': {}}
            - {'chance': 0.2, 'module': 'imgaug.augmenters.imgcorruptlike', 'type': 'Fog',                        'kwargs': {'severity': 2}}
        train_geometric_transforms:
            - {'chance': 0.5, 'module': 'imgaug.augmenters', 'type': 'Flipud', 'kwargs': {}}
            - {'chance': 0.5, 'module': 'imgaug.augmenters', 'type': 'Fliplr', 'kwargs': {}}
            - {'chance': 0.2, 'module': 'imgaug.augmenters', 'type': 'Rotate', 'kwargs': {'rotate': !!python/tuple [-90, 90], 'mode': 'symmetric'}}
        val_photometric_transforms: null
        val_geometric_transforms: null
        test_photometric_transforms: null
        test_geometric_transforms: null
        load_images: True
callbacks:
    - module: pytorch_lightning.callbacks
      name: ModelCheckpoint
      kwargs: {
        "monitor": "val/loss",
        "mode": "min"
      }
model:
    predictor: {
        module: "models",
        name: "VarResNet",
        kwargs: {
            "in_channels": 42, # (seq_len-1)*3
            "out_features": 8,
            "name": "resnet50",
            "pretrained": False
        }
    }
    optimizer: {
        module: "torch.optim",
        name: "Adam",
        kwargs: {
            "lr": 2.5e-5,
            "betas": [0.9, 0.999]
        }
    }
    loss: {
        module: "torch.nn",
        name: "PairwiseDistance",
        kwargs: {}
    } 
    scheduler: {
        module: "torch.optim.lr_scheduler",
        name: "MultiStepLR",
        kwargs: {
            "milestones": [50, 75],
            "gamma": 0.5,
            "verbose": True
        }
    }
